baseurl = "/"
languageCode = "en-us"
title = "Bas Machielsen"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blogs/"
    weight = 2
[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 3
[[menu.main]]
    name = "Classes"
    url = "/classes/"
    weight = 4
[[menu.main]]
    name = "R Packages"
    url = "/packages/"
    weight = 5
[[menu.main]]
    name = "Data"
    url = "/data/"
    weight = 6


[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "bas_m.png"
    width = 60
    height = 60
    alt = "Logo"
    

